version: '3'
services:
  app1:
    build: ./fiberapp1
    ports:
    - "3001:3000"
  app2:
    build: ./fiberapp2
    ports:
    - "3002:3000"
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2